name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  build-readme-file:
    runs-on: ubuntu-latest
    steps:
      # Checkout, install tools..
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run lint
      # Save files.
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: '[ci skip] Automatic file changes/fix'
          branch: 'master'
          file_pattern: ':/*.*'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

